CREATE TABLE CLIENTES(
    id INT NOT NULL AUTO_INCREMENT,
    dni VARCHAR(9) NOT NULL UNIQUE,
    nombre TEXT,
    fecha_alta DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE TABLE TELEFONOS(
    id INT NOT NULL AUTO_INCREMENT,
    numero VARCHAR(13) NOT NULL,
    fecha_contrato TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    id_cliente INT,

    PRIMARY KEY(id),
    FOREIGN KEY (id_cliente) REFERENCES CLIENTES(id) ON DELETE SET NULL
);


INSERT INTO CLIENTES (dni, nombre) VALUES ('12345678A', 'Isaac Torres');

INSERT INTO TELEFONOS (numero, id_cliente) VALUES ('+34600111222', 1)
